name: Upstream and Downstream CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  run_upstream_and_downstream_ci:
    name: Upstream and Downstream CI
    runs-on: ubuntu-latest
    env:
      DBT_CLOUD_SERVICE_TOKEN: ${{ secrets.DBT_CLOUD_SERVICE_TOKEN }}
      DBT_CLOUD_ACCOUNT_ID: 43786
      UPSTREAM_JOB_ID: 106109
      DOWNSTREAM_JOB_ID: 106366
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run python script
        run: python scripts/dependent_ci.py
